# PactStream linting rules
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "lib/l10n/**"

  plugins:
    - custom_lint

linter:
  rules:
    # Estilo
    - prefer_single_quotes
    - avoid_print
    - require_trailing_commas
    - sort_pub_dependencies

    # Seguridad
    - avoid_dynamic_calls
    - avoid_returning_null_for_future
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks

    # Performance
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

    # Mantenibilidad
    - always_declare_return_types
    - avoid_classes_with_only_static_members
    - avoid_catching_errors
    - prefer_final_fields
    - prefer_final_locals
    - sort_constructors_first
    - unnecessary_lambdas
    - use_super_parameters
